/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsTap {
  function: (...args: any[]) => any
  stage: number
}
export const enum RegisterJsTapKind {
  BeforeRun = 0,
  BeforeRunSync = 1
}
export interface RegisterJsTaps {
  registerBeforeRunTaps: (stages: Array<number>) => Array<{ function: ((arg: string) => void); stage: number; }>
  registerBeforeRunSyncTaps: (stages: Array<number>) => Array<{ function: ((arg: string) => void); stage: number; }>
}
export interface RawOutput {
  path: string
  filename: string
}
export interface RawConfig {
  root: string
  entry: string
  output: RawOutput
}
export declare class RsWebpack {
  constructor(rawConfig: RawConfig, registerJsTaps: RegisterJsTaps)
  run(): Promise<void>
  setNonSkippableRegisters(kinds: Array<RegisterJsTapKind>): void
}
export declare class JsCompiler { }
